context:
  name: libplacebo
  version: "7.360.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/haasn/libplacebo/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d05fdf90bea2f629eaa2d115e909fd356388ac639e54f77b87a018a6d76224bd

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - cmake
    - pkg-config
    - meson
    - jinja2
    - python <3.13 # pins python to compatible version for meson
  host:
    - libdovi
    - fast_float
    - lcms2
    - markupsafe
    - libvulkan-headers
    - libvulkan-loader
    - shaderc
    - xxhash
  run_exports:
    - ${{ pin_subpackage('libplacebo', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      - xxhash

tests:
  - package_contents:
      lib:
        - libplacebo
  - script:
      - if pkg-config --exists libplacebo; then echo "Libplacebo found"; else echo "Libplacebo not found"; exit 1; fi
    requirements:
      run:
        - pkg-config

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Core rendering algorithms and ideas from mpv as an independent library
  description: |
    Libplacebo is, in a nutshell, the core rendering algorithms and ideas of
    mpv rewritten as an independent library. It provides robust and efficient
    GPU rendering for a variety of multimedia applications.
  homepage: https://code.videolan.org/videolan/libplacebo

extra:
  recipe-maintainers:
    - ndeybach
    - Tobias-Fischer
